In [4]:
import pandas as pd

In [14]:

df = pd.read_pickle('Str_Bench_RET.pkl')
df

           Date  Strat_Ret  Bench_Ret
0    2013-05-23  -0.004857  -0.003551
1    2013-05-24  -0.002945  -0.001320
2    2013-05-28   0.006070   0.007137
3    2013-05-29  -0.013526  -0.007611
4    2013-05-30   0.006074   0.004364
...         ...        ...        ...
3227 2026-03-24   0.018806  -0.000862
3228 2026-03-25  -0.010812   0.003548
3229 2026-03-26  -0.010563  -0.037594
3230 2026-03-27   0.003166   0.007888
3231 2026-03-30   0.007897   0.003793

[3232 rows x 3 columns]

In [16]:
df.Date

0      2013-05-23
1      2013-05-24
2      2013-05-28
3      2013-05-29
4      2013-05-30
          ...
3227   2026-03-24
3228   2026-03-25
3229   2026-03-26
3230   2026-03-27
3231   2026-03-30
Name: Date, Length: 3232, dtype: datetime64[ns]

In [10]:
df = pd.read_pickle('full_backtest_and_real_time.pkl')
df

            Full_Backtest  Real_Time
Date
2013-05-28       0.006071        NaN
2013-05-29      -0.013527        NaN
2013-05-30       0.006074        NaN
2013-05-31      -0.025349        NaN
2013-06-03       0.008268        NaN
...                   ...        ...
2026-03-26      -0.015293  -0.010563
2026-03-27      -0.007846   0.003166
2026-03-30       0.000555        NaN
2026-03-31       0.026060        NaN
2026-04-01       0.006358   0.007897

[3232 rows x 2 columns]

In [6]:
df[df.Date >= '2025-10-23']

           Date  Strat_Ret  Bench_Ret
3131 2025-10-23   0.022509  -0.000774
3132 2025-10-23   0.022509  -0.001243
3133 2025-10-23   0.022509  -0.003275
3134 2025-10-23   0.022509   0.004069
3135 2025-10-23   0.022509   0.002231
3136 2025-10-23   0.022509   0.005652
3137 2025-10-23   0.022509  -0.006843

In [2]:
2+2

4